version = 0.1
[default.deploy.parameters]
stack_name = "text-it-to-me-doc"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
region = "ap-northeast-1"
resolve_s3 = true
confirm_changeset = true
parameter_overrides = "BedrockModelId=\"jp.anthropic.claude-sonnet-4-6\" SesFromEmail=\"noreply@jaycloud.net\""
